name: dev
on: [ push, pull_request ]
jobs:
  skip:
    runs-on: ec2-gardenlinux-amd64
    steps:
      - run: true
  # build:
  #   uses: ./.github/workflows/build.yml
  #   with:
  #     version: today
