name: release
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        default: beta
        options:
        - beta
        - stable
      version:
        required: true
        type: string
      commit:
        required: true
        type: string
jobs:
  create_release:
    runs-on: ec2-gardenlinux-amd64
    steps:
      - uses: actions/checkout@v2
      - name: create GitHub release
        run: .github/workflows/release.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} create "${{ inputs.type == 'beta' && 'beta_' || '' }}${{ inputs.version }}" "${{ inputs.version }}" > .github_release
      - uses: actions/upload-artifact@v2
        with:
          name: release
          path: .github_release
  upload_to_release:
    needs: create_release
    runs-on: ec2-gardenlinux-amd64
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
        target: [ kvm, kvm-secureboot, metal, metal-secureboot, gcp, aws, azure, ali, openstack, vmware, pxe, firecracker, github_action_runner, metalv ]
        modifier: [ "" ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: release
      - run: |
          release="$(cat .github_release)"
          echo "$release"
          features="$(cat "make_targets/${{ matrix.target }}")"
          echo "$features"
          cname="$(./bin/garden-feat cname --features "$features")"
          echo "$cname"
          s3_yaml="s3://gardenlinux-github-releases/meta/singles/$cname-${{ matrix.architecture }}-${{ inputs.version }}-${{ inputs.commit }}"
          echo "$s3_yaml"
      # - uses: actions/download-artifact@v2
      #   with:
      #     name: build-${{ matrix.architecture }}-${{ matrix.target }}${{ matrix.modifier }}
      #     path: .build
      # - run: |
      #     release="$(cat .github_release)"
      #     find .build -type f | .github/workflows/release.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.repository }} upload "$release"
